### ISSUE TITLE
FFT Meta Issue

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#415]
This issue is for communicating plans for the FFT module and tracking github issues. 
I'll try to keep it up to date.

**API Boundary**
In order to make the `irfft` module re-usable for scripts (even outside Orange), it has minimal dependencies and no knowledge of Orange Table data structures.
However, the actual implementation is overly complex and leaves too much of that complexity in the GUI OWFFT side.

- [ ] Move last bits of data wrangling out of OWFFT back into irfft
- [ ] Simplify irfft calculation code to make it more readable/clear, esp phase calculation
- [ ] Add preprocessor-style layer for use in Orange scripts. May or may not actually be a preprocessor but should accept an Orange.Table like a preprocessor

**GUI / User-friendliness**
Mostly small things, except responsive changes which will build on the API fixes above.

 - [ ] Make responsive / cancel-able as in #398 and friends
 - [ ] Load and use stored zpd values (#414)
 - [ ] Provide user feedback on zpd (#250)
 - [ ] Handle (and test) multi-spectra stored phase / zpd condition #(253)
 - [ ] load / use parameters from Table attributes instead of metadata (#272)
 - [ ] Documentation (#254)

**s-SNOM**
People would like to do FFT on s-SNOM data. There are just a few missing pieces:

 - [ ] Happ-Genzel apodization
 - [ ] Hann apodization
 - [ ] Subtraction phase correction
 - [ ] Example workflow

**Speed**
Some progress (5-10x) was done in #413 but true multi-core processing is still not implemented

 - [ ] Multiprocessing (#360)

**Comment by levandoskije** [comment]
Hey, @stuart-cls , I'm working on a complex FFT to process NeaSNOM data with synchrotron radiation.

**Comment by raul-freitas** [comment]
Hello @stuart-cls, @levandoskije  above is my student and we were about to contact you about our development on the FFT module for s-SNOM data. One of the main points is that s-SNOM is intrinsically complex so we need to apply a FFT instead of a Re-FFT. We already implemented the in the Multiple widget the reading of Amplitude and Phase of the s-SNOM data. Now, we have a quasi-finished version of the FFT widget for this class of data.

**Comment by borondics** [comment]
Hi @raul-freitas, @levandoskije, and @stuart-cls,

Since we don't have the luxury of a few hundred programmers I think it would be great to coordinate the work everyone does not to duplicate code. This should however not prevent us to review and rewrite parts that are not up to requirements.

@stuart-cls: thanks for posting the list above. I think you could even put together a [team](https://github.com/orgs/Quasars/teams), make a [project](https://github.com/Quasars/orange-spectroscopy/projects) and define milestones on GitHub.

@levandoskije, @raul-freitas: is the new widget available for testing? I think your contribution is great and very important for many colleagues (e.g. ALS and hopefully others soon). I sent invites to both of you on Github, please check your accounts to join the Quasars team.

**Comment by stuart-cls** [comment]
Thanks all for the great response!
I got most of my starting points for the s-SNOM section from chatting with @ok-nc.
Since there is a lot of interest specifically in the s-SNOM processing, let's move this to a new issue. If necessary we can add projects and things as @borondics suggests.
